name: SDK Type Check

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1-5' # weekly run
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  typecheck-latest:
    uses: wormhole-foundation/workflows/.github/workflows/wormhole-demo-typecheck.yml@3d6ccc988ec1949b31751a30845151b979987246 # main
